### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by krychaj5** [Jire/Charlatano#1005]
I'm using latest Charlatano@1.2.3 and when I'm running Start charlatano.bat file when I'm in game, cheat doesnt load and i have this in CMD console: 

`Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.charlatano.game.netvars.NetVars.load(NetVars.kt:46)
        at com.charlatano.game.CSGO.initialize(CSGO.kt:114)
        at com.charlatano.Charlatano.main(Charlatano.kt:69)
Caused by: java.lang.IllegalStateException
        at com.charlatano.game.offsets.Offset$Companion.cachedBytes(Offset.kt:50)
        at com.charlatano.game.offsets.Offset$Companion.access$cachedBytes(Offset.kt:36)
        at com.charlatano.game.offsets.Offset.<init>(Offset.kt:58)
        at com.charlatano.game.offsets.ModuleScan.invoke(ModuleScan.kt:37)
        at com.charlatano.game.offsets.ClientOffsets.<clinit>(ClientOffsets.kt:30)
        ... 3 more`
        
 I've updated java on my computer and restarted system - still not working

**Comment by ruper3734** [comment]
me too
