### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Gooby0414** [Jire/Charlatano#1008]
I am not very good with Java so if you can please help.
Everytime I run the start it goes
Exception in thread "main" javax.script.ScriptException: Unresolved reference: True
Unresolved reference: True
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.asJsr223EvalResult(KotlinJsr223JvmScriptEngineBase.kt:104)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:63)
        at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.compileAndEval(KotlinJsr223ScriptEngineImpl.kt:94)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:94)
        at com.charlatano.Charlatano.main(Charlatano.kt:44)
Press any key to continue . . .

I have all the Java paths hooked up
Version: 1.2.3

**Comment by Gooby0414** [comment]
Edit: I have now fixed that: Exception in thread "Thread-4" java.lang.NullPointerException
        at com.charlatano.game.CSGO$initialize$$inlined$every$2.invoke(Every.kt:42)
        at com.charlatano.game.CSGO$initialize$$inlined$every$2.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
AL lib: (EE) alc_cleanup: 1 device not closed
Only happens while im in csgo so
