### ISSUE TITLE
 Can someone help me? I'm getting this message.

### ISSUE THREAD

**Issue by wesleybs29** [Jire/Charlatano#1027]
Exception in thread "Thread-8" java.lang.IllegalStateException: Failed to resolve offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:62)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:30)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:69)
        at com.charlatano.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at com.charlatano.game.ClientStateKt.angle(ClientState.kt:33)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt:64)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "Thread-5" java.lang.IllegalStateException: Failed to resolve offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:62)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:30)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:69)
        at com.charlatano.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at com.charlatano.game.ClientStateKt.angle(ClientState.kt:33)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:59)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
-Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.util.Scanner.nextLine(Unknown Source)
        at com.charlatano.Charlatano.main(Charlatano.kt:79)

**Comment by udansabor** [comment]
getting this message also. And nothing happens in game. Nothing change
![error](https://user-images.githubusercontent.com/56051520/125162719-15abfd80-e192-11eb-9ac6-70d91c34a4f4.PNG)

**Comment by Kansaidorifto86** [comment]
same problem
