### ISSUE TITLE
Need answers. #jireplease

### ISSUE THREAD

**Issue by JovanCxe** [Jire/Charlatano#1045]
Hello @Jire , 

Can you please upgrade tutorial how to prepare and use this cheat?
I dont know which verison of Java JDK I need to install and when I finally succeed to build, when I start cheat I got message:

"thread-2" java.lang.nullpointerexception at com.charlatano.game.csgo$initialize$$inlined$every$2.invoke(every.kt:42) at com.charlatano.game.csgo$initialize$$inlined$every$2.invoke(every.kt) at kotlin.concurrent.threadskt$thread$thread$1.run(thread.kt:30)

And cheat didnt work..
Please can you put some news about this, are this is still work or no? Thanks

**Comment by gdaxz** [comment]
yeah that would be cool. how did you compile the cheat? I am unable.
