### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by fraudsAppdupe** [Jire/Charlatano#106]
Unzipping C:\Users\XXX\.gradle\wrapper\dists\gradle-3.5-all\exhrs6ca08n232b14ue48lbye\gradle-3.5-all.zip to C:\Users\XXX\.gradle\wrapper\dists\gradle-3.5-all\exhrs6ca08n232b14ue48lbye
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

i got this error not sure why

**Comment by Jire** [comment]
Your PC computer name cannot be "XXX."

**Comment by fraudsAppdupe** [comment]
i delete the .grade folder in my profile now is working fine.
