### ISSUE TITLE
random bug

### ISSUE THREAD

**Issue by Rorky** [Jire/Charlatano#111]
while i was playing it stoped working

received this error (i've rebuilt it)

`Exception in thread "main" javax.script.ScriptException: error: incomplete code
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:67)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
eval(KotlinJsr223JvmScriptEngineBase.kt:32)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:68)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)
Press any key to continue . . .`

**Comment by Rorky** [comment]
nvm my dumbass input wrong code
