### ISSUE TITLE
Error after cheat update (Kotlin 1.1-2.3, Offset Pattern Update)

### ISSUE THREAD

**Issue by punkjj** [Jire/Charlatano#123]
Exception in thread "Thread-5" Exception in thread "Thread-4" kotlin.KotlinNullP
ointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFFlags(NetVarOffsets.kt)

        at com.charlatano.game.entity.PlayerKt.flags(Player.kt:58)
        at com.charlatano.game.entity.PlayerKt.onGround(Player.kt:60)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt:34
)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(E
very.kt:31)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(E
very.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getIShotsFired(NetVarOffset
s.kt)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:36)

        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-10" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFlFlashMaxAlpha(NetVarOf
fsets.kt)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt:32)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.
invoke(Every.kt:31)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.
invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-7" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getHActiveWeapon(NetVarOffs
ets.kt)
        at com.charlatano.game.entity.PlayerKt.weapon(Player.kt:47)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.inv
oke(Every.kt:44)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.inv
oke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-3" java.lang.IllegalStateException: Failed to resolv
e offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:61)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:29)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:68)
        at com.charlatano.game.offsets.ClientOffsets.getDwGlowObject(ClientOffse
ts.kt)
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inline
d$every$1.invoke(Every.kt:36)
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inline
d$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by punkjj** [comment]
@Jire

**Comment by BrunoSammartino** [comment]
Same Error

**Comment by DeathStrax** [comment]
Same error too. After I edited the .kts settings file.

My earlier post was due to me replacing the settings file with the Charlatano 0.9.8 to the latest version.

Strange....

**Comment by anurag01021996** [comment]
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --statu
s for details
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler-run
ner/1.1.2-2/kotlin-compiler-runner-1.1.2-2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-annotation-p
rocessing/1.1.2-2/kotlin-annotation-processing-1.1.2-2.jar
:compileKotlin
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-script-util/
1.1.2-2/kotlin-script-util-1.1.2-2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-script-runti
me/1.1.2-2/kotlin-script-runtime-1.1.2-2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler/1.1
.2-2/kotlin-compiler-1.1.2-2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-daemon-clien
t/1.1.2-2/kotlin-daemon-client-1.1.2-2.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-script-util/
1.1.2-2/kotlin-script-util-1.1.2-2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-script-runti
me/1.1.2-2/kotlin-script-runtime-1.1.2-2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler/1.1
.2-2/kotlin-compiler-1.1.2-2.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-daemon-clien
t/1.1.2-2/kotlin-daemon-client-1.1.2-2.jar
Using kotlin incremental compilation
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into
them. This may cause difficult to debug problems if there's a different version
of the Kotlin Runtime library in the classpath. Consider removing these librarie
s from the classpath or use '-Xskip-runtime-version-check' to suppress this warn
ing
w: C:\Users\pc\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-co
mpiler\1.1.2-2\88d0e4bdde9e6a33a6b6c900d85a49c3cf3e8f12\kotlin-compiler-1.1.2-2.
jar: Library has Kotlin runtime bundled into it
:compileJava
Note: C:\Users\pc\Downloads\Charlatano-master (2)\Charlatano-master\src\main\jav
a\com\intellij\openapi\util\io\FileSystemUtil.java uses unchecked or unsafe oper
ations.
Note: Recompile with -Xlint:unchecked for details.
:copyMainKotlinClasses
:processResources NO-SOURCE
:classes
:shadowJar
:charlatano

BUILD SUCCESSFUL

Total time: 4 mins 45.14 secs
Press any key to continue . . .


ii compiled the build successfully...now going to test it

**Comment by anurag01021996** [comment]
negative-the build doesn't work....following are the errors when i start charlatano

Exception in thread "Thread-5" Exception in thread "Thread-4" kotlin.KotlinNullP
ointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFFlags(NetVarOffsets.kt)

        at com.charlatano.game.entity.PlayerKt.flags(Player.kt:58)
        at com.charlatano.game.entity.PlayerKt.onGround(Player.kt:60)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt:34
)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(E
very.kt:31)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(E
very.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getIShotsFired(NetVarOffset
s.kt)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:36)

        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-10" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFlFlashMaxAlpha(NetVarOf
fsets.kt)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt:32)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.
invoke(Every.kt:31)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.
invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-7" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getHActiveWeapon(NetVarOffs
ets.kt)
        at com.charlatano.game.entity.PlayerKt.weapon(Player.kt:47)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.inv
oke(Every.kt:44)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.inv
oke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-3" java.lang.IllegalStateException: Failed to resolv
e offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:61)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:29)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:68)
        at com.charlatano.game.offsets.ClientOffsets.getDwGlowObject(ClientOffse
ts.kt)
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inline
d$every$1.invoke(Every.kt:36)
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inline
d$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by M4jx** [comment]
Do you have Java SDK ?

**Comment by anurag01021996** [comment]
I have latest jdk and java_home path is also done
I successfully completed the build too....but after I run it....same errors
were shown in charlatanism cmd window

**Comment by M4jx** [comment]
Same here

**Comment by Balouchis** [comment]
same

**Comment by Sababdb** [comment]
punkjj can u share ur file so I can download it?

**Comment by Jire** [comment]
Fixed with [1.0.1](https://github.com/Jire/Charlatano/releases/tag/1.0.1)
