### ISSUE TITLE
What JAVA should we use with Charalaton 1.0.1

### ISSUE THREAD

**Issue by Balouchis** [Jire/Charlatano#128]
Should we use latest version of java or older version that we used in 0.9.8? Any Idea?
@Jire 
Thanks,

**Comment by Balouchis** [comment]
Exception in thread "Thread-5" Exception in thread "Thread-4" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getIShotsFired(NetVarOffsets.kt)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:36)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFFlags(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.flags(Player.kt:58)
        at com.charlatano.game.entity.PlayerKt.onGround(Player.kt:60)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt:34)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(Every.kt:31)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-7" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getHActiveWeapon(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.weapon(Player.kt:47)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt:44)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-10" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFlFlashMaxAlpha(NetVarOffsets.kt)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt:32)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.invoke(Every.kt:31)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-6" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getITeamNum(NetVarOffsets.kt)
        at com.charlatano.game.entity.EntityKt.team(Entity.kt:50)
        at com.charlatano.scripts.esp.GlowESPKt$glowEsp$$inlined$every$1.invoke(Every.kt:65)
        at com.charlatano.scripts.esp.GlowESPKt$glowEsp$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Still. lol

**Comment by Jire** [comment]
You need to use the latest cheat which is 1.0.1

**Comment by apples12** [comment]
I'm using latest update (1.0.1) and I am getting a few errors so I did a fresh install and is now only getting one error:

Exception in thread "main" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.ClassTable$name$2.invoke(ClassTable.kt:34)
        at com.charlatano.game.netvars.ClassTable$name$2.invoke(ClassTable.kt:28)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.netvars.ClassTable.getName(ClassTable.kt)
        at com.charlatano.game.netvars.NetVars.load(NetVars.kt:49)
        at com.charlatano.game.CSGO.initialize(CSGO.kt:115)
        at com.charlatano.Charlatano.main(Charlatano.kt:42)

**Comment by Balouchis** [comment]
@Jire It is giving same error! :(

**Comment by Balouchis** [comment]
It also gives someking of bugs at building see below Picture!
![capture](https://cloud.githubusercontent.com/assets/28670883/26273383/c8afdab6-3d48-11e7-9258-2ff95231eaa5.JPG)

**Comment by Balouchis** [comment]
Then after I start it with my CSGO it gives following error!
![capture](https://cloud.githubusercontent.com/assets/28670883/26273421/81c33cd2-3d49-11e7-9160-08f14cba5621.JPG)

**Comment by Jire** [comment]
Fixed in [1.0.2](https://github.com/Jire/Charlatano/releases/tag/1.0.2)
