### ISSUE TITLE
Netvar Error when launching

### ISSUE THREAD

**Issue by Aerodynamic156** [Jire/Charlatano#129]
I get a netvar error when after I launch Charlatano.
Exception in thread "Thread-5" Exception in thread "Thread-4" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getIShotsFired(NetVarOffsets.kt)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:36)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFFlags(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.flags(Player.kt:58)
        at com.charlatano.game.entity.PlayerKt.onGround(Player.kt:60)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt:34)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(Every.kt:31)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-10" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFlFlashMaxAlpha(NetVarOffsets.kt)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt:32)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.invoke(Every.kt:31)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-7" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getHActiveWeapon(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.weapon(Player.kt:47)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt:44)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by Balouchis** [comment]
Go and delete the file .grade from C:\user\yourusername\.gradle and try build again it will redownload it!

**Comment by Balouchis** [comment]
It worked for me lol

**Comment by apples12** [comment]
@Balouchis 

Did that still get an error with "main"

**Comment by Jire** [comment]
Fixed in [1.0.2](https://github.com/Jire/Charlatano/releases/tag/1.0.2)
