### ISSUE TITLE
Charlatano 1.0.1

### ISSUE THREAD

**Issue by Balouchis** [Jire/Charlatano#130]
@Jire I figured out about the errors I just deleted .gradle file from my C:\users\noname\ .gradle and then I build all worked fine no error then when I started Charlatano 1.0.1 still it didn't give error but still it is not working see below picture ? Any idea ?

![capture](https://cloud.githubusercontent.com/assets/28670883/26273598/6d6f3b98-3d4c-11e7-9623-2a63eca39f37.JPG)

**Comment by apples12** [comment]
Did what you did and reinstalled it and all and I get one error that does not change.

Exception in thread "main" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.ClassTable$name$2.invoke(ClassTable.kt:34)
        at com.charlatano.game.netvars.ClassTable$name$2.invoke(ClassTable.kt:28)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.netvars.ClassTable.getName(ClassTable.kt)
        at com.charlatano.game.netvars.NetVars.load(NetVars.kt:49)
        at com.charlatano.game.CSGO.initialize(CSGO.kt:115)
        at com.charlatano.Charlatano.main(Charlatano.kt:42)

**Comment by Balouchis** [comment]
:( yeah now it gives

**Comment by Jire** [comment]
Fixed https://github.com/Jire/Charlatano/releases/tag/1.0.2
