### ISSUE TITLE
This error shows up in console

### ISSUE THREAD

**Issue by davewolax** [Jire/Charlatano#151]
`Exception in thread "Thread-8" java.lang.IllegalStateException: Failed to resolve offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:62)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:30)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:69)
        at com.charlatano.game.offsets.ClientOffsets.getDwSensitivityPtr(ClientOffsets.kt)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt:33)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.settings.AdvancedKt.getGAME_SENSITIVITY(Advanced.kt)
        at com.charlatano.utils.AimKt.pathAim(Aim.kt:79)
        at com.charlatano.utils.AimKt.pathAim$default(Aim.kt:73)
        at com.charlatano.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt:81)
        at com.charlatano.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Exception in thread "Thread-5" java.lang.IllegalStateException: Failed to resolve offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:62)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:30)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:69)
        at com.charlatano.game.offsets.ClientOffsets.getDwSensitivityPtr(ClientOffsets.kt)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt:33)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.settings.AdvancedKt.getGAME_SENSITIVITY(Advanced.kt)
        at com.charlatano.utils.AimKt.pathAim(Aim.kt:79)
        at com.charlatano.utils.AimKt.pathAim$default(Aim.kt:73)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:74)`

**Comment by Semper-r** [comment]
i have these:

Exception in thread "Thread-7" java.lang.IllegalStateException: Failed to resolve offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:62)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:30)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:69)
        at com.charlatano.game.offsets.ClientOffsets.getDwSensitivityPtr(ClientOffsets.kt)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt:33)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.settings.AdvancedKt.getGAME_SENSITIVITY(Advanced.kt)
        at com.charlatano.utils.AimKt.pathAim(Aim.kt:79)
        at com.charlatano.utils.AimKt.pathAim$default(Aim.kt:73)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:74)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by davewolax** [comment]
@Semper-r @Jire I think this is because of the new update that came out.

**Comment by Semper-r** [comment]
yes, also the aim bot fov is less not in the kts file but in practice

**Comment by Semper-r** [comment]
and the rcs doesnt work for me no longer

**Comment by ricabook** [comment]
Hey guys..
I don't believe the new update is the problem. After 1.02 i'm using normally and even with the last CS update (23/05) all the scripts are working fine.

**Comment by meister15** [comment]
@ricabook 
Not working man problem csgo last update

**Comment by ricabook** [comment]
Still working here, @meister15!
![20170524141752_1](https://cloud.githubusercontent.com/assets/28607535/26416451/4b84c99c-408c-11e7-82ce-0c8ee98761d6.jpg)

**Comment by ricabook** [comment]
Still working here, @meister15:
![20170524141752_1](https://cloud.githubusercontent.com/assets/28607535/26416567/b2265256-408c-11e7-8136-c0a084650aa6.jpg)

**Comment by meister15** [comment]
Add me on skype nenadpetrovic91


24.05.2017. 19.22, "ricabook" <notifications@github.com> је написао/ла:

**Comment by Kruckash** [comment]
For anyone getting this issue (including the gray overlay box) Check #90 :)
..And learn to follow step by step guides.. jeez

**Comment by meister15** [comment]
@ricabook 
am windows 7 
you?

**Comment by ricabook** [comment]
Win 10

Did u check issue #90 ?

**Comment by Is82jM** [comment]
U are fucking retarded man, this cheat use automatic offsets update. I played with this hack today after this update it's still works like a charm.

**Comment by anurag01021996** [comment]
@ricabook bro..can u share your build? tx

**Comment by ricabook** [comment]
@anurag01021996 I just made all the steps on Issue #90 .
Really can't help u guys! Sorry

**Comment by gfreivasc** [comment]
It is a non-breaking error. Also happens with me. Always. But never crashes or anything

**Comment by anurag01021996** [comment]
@ricabook bro....its a 1  minute work...u can uplaod on any cloud

**Comment by davewolax** [comment]
Exception in thread "Thread-5" java.lang.IllegalStateException: Failed to resolve offset
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:62)
        at com.charlatano.game.offsets.Offset$address$2.invoke(Offset.kt:30)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.offsets.Offset.getAddress(Offset.kt)
        at com.charlatano.game.offsets.Offset.getValue(Offset.kt:69)
        at com.charlatano.game.offsets.ClientOffsets.getDwSensitivityPtr(ClientOffsets.kt)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt:33)
        at com.charlatano.settings.AdvancedKt$GAME_SENSITIVITY$2.invoke(Advanced.kt)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.settings.AdvancedKt.getGAME_SENSITIVITY(Advanced.kt)
        at com.charlatano.utils.AimKt.pathAim(Aim.kt:79)
        at com.charlatano.utils.AimKt.pathAim$default(Aim.kt:73)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:74)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Press any key to continue . . .

**Comment by kokolino1** [comment]
the esp is working fine with bhop, but everything else doesn't.

**Comment by Semper-r** [comment]
@kokolino1 so your esp only works when you have bhop on?

**Comment by Jire** [comment]
Try out the latest release [1.0.3](https://github.com/Jire/Charlatano/releases/tag/1.0.3)

**Comment by meister15** [comment]
Instal windows 10 profesional and work esp, bhop fine.


25.05.2017. 12.43, "Thomas Nappo" <notifications@github.com> је написао/ла:

**Comment by meister15** [comment]
Esp and bhop

25.05.2017. 14.10, "anurag01021996" <notifications@github.com> је
написао/ла:

**Comment by anurag01021996** [comment]
@Jire I am running win 8.1 and i just compiled 1.0.3....following console errors came and cheat didnt work
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 1024
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inline
d$every$1.invoke(Every.kt:46)
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inline
d$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
