### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Miromursa** [Jire/Charlatano#228]
After some time i get this error message : 

Exception in thread "Thread-13" kotlin.KotlinNullPointerException
        at com.charlatano.game.entity.BombKt.location(Bomb.kt:51)
        at com.charlatano.scripts.BombTimerKt$bombTimer$$inlined$invoke$1.invoke(Every.kt:41)
        at com.charlatano.scripts.BombTimerKt$bombTimer$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by Jire** [comment]
Fixed with https://github.com/Jire/Charlatano/commit/f73986ced3b2894ddbe206da30818cc044856fe5
