### ISSUE TITLE
GAME CRASH WHEN I PRESS "B' TO BUY 

### ISSUE THREAD

**Issue by wuwujia** [Jire/Charlatano#238]
Exception in thread "Thread-11" kotlin.KotlinNullPointerException
        at com.charlatano.game.entity.BombKt.location(Bomb.kt:51)
        at com.charlatano.scripts.BombTimerKt$bombTimer$$inlined$invoke$1.invoke(Every.kt:41)
        at com.charlatano.scripts.BombTimerKt$bombTimer$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by w-o-a-h** [comment]
remove bomb timer bind idk

**Comment by Jire** [comment]
Are you using an old version? Like before 1.0.5-HOTFIX?

**Comment by wuwujia** [comment]
No.I'm using the 1.0.5 hotfix the latest version. and this crashed just went away the past 3 days.  Maybe it's just me by the odds.

BTW, when I used JDK to build your java project , it's successful but not 100% succesful.
