### ISSUE TITLE
Getting Error  1.0.5

### ISSUE THREAD

**Issue by pakboy** [Jire/Charlatano#295]
Exception in thread "Thread-1" kotlin.UninitializedPropertyAccessException: lateinit property hwnd has not been initialized
        at com.charlatano.overlay.Overlay.getHwnd(Overlay.kt:41)
        at com.charlatano.game.CSGO$initialize$$inlined$every$1.invoke(Every.kt:39)
        at com.charlatano.game.CSGO$initialize$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

These error I get in console How To Fix [Him](url) 
using window 10
![capture_2017_07_20_21_35_43_114](https://user-images.githubusercontent.com/25552893/28429356-435c746e-6d31-11e7-9014-a1a8c3196d3d.png)

**Comment by pakboy** [comment]
@Jire Delete him 
I get 1.0.6 Working great

**Comment by MoofMonkey** [comment]
Close please....

**Comment by MoofMonkey** [comment]
Wow, @Jire alive
