### ISSUE TITLE
Cheat not working

### ISSUE THREAD

**Issue by M4jx** [Jire/Charlatano#304]
Windows 8.1 pro
Installed Java SDK
Compiled the cheat
In middle of a game
Starting the cheat all default settings 

Exception in thread "Thread-1" kotlin.UninitializedPropertyAccessException: late
init property hwnd has not been initialized
        at com.charlatano.overlay.Overlay.getHwnd(Overlay.kt:41)
        at com.charlatano.game.CSGO$initialize$$inlined$every$1.invoke(Every.kt:
39)
        at com.charlatano.game.CSGO$initialize$$inlined$every$1.invoke(Every.kt)

        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by ikrypt0** [comment]
only works on windows 7 and 10

**Comment by Jire** [comment]
You need to use 1.0.5-HOTFIX or the master branch, 1.0.5 suffers from the bug you posted.
