### ISSUE TITLE
Adding a glow_key function

### ISSUE THREAD

**Issue by 4103** [Jire/Charlatano#320]
Hey developer perons,

I made a small change to toggle GlowESP on the  ALT_Key just wrapping an `if(keyPressed(18)){do esp pseudo code}` which worked fine. 
Now I want to extend that so that I have USE_GLOW_KEY and GLOW_KEY in the Settings file and can change stuff from there. It compiles using the build.bat but crashes with following errors when starting:

```
Exception in thread "main" org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_5
Cause: Cannot find package fragment for file Line_5.kts with package com.charlatano.settings
File being compiled and position: (30,1) in /Line_5.kts
PsiElement: var SKELETON_ESP = false

/**
 * Whether or not to use box ESP.
 */
var BOX_ESP = false

/**
 * Whether or not to use the within-game glow ESP.
 *
 * This ESP **CANNOT** be hidden from game capture for streaming.
 */
var GLOW_ESP = true


///////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////// --- TOGGLES --- ////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Whether or not to highlight your team mates.
 */
var SHOW_TEAM = true

/**
 * Whether or not to highlight enemies.
 */
var SHOW_ENEMIES = true

/**
 * Whether or not to highlight "dormant" (unknown-location) players.
 *
 * Enabling this can allow you to see players at a further distance,
 * but you may see some "ghost" players which are really not there.
 */
var SHOW_DORMANT = false

/**
 * Whether or not to highlight the bomb.
 */
var SHOW_BOMB = true

/**
 * Whether or not to highlight weapons.
 */
var SHOW_WEAPONS = false

/**
 * Whether or not to highlight grenades.
 */
var SHOW_GRENADES = false

/**
 * Use a Glow toogle
 */
var USE_GLOW_KEY = true

/**
 * Set VirtualKeyCode for the toggle
 */
var GLOW_KEY = 18
///////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////// --- COLORS --- ///////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////

/**
 * The color to highlight your team mates.
 */
var TEAM_COLOR = Color(0, 0, 255)

/**
 * The color to highlight your enemies.
 */
var ENEMY_COLOR = Color(255, 0, 0)

/**
 * The color to highlight the bomb.
 */
var BOMB_COLOR = Color(255, 255, 0, 1.0)

/**
 * The color to highlight weapons.
 */
var WEAPON_COLOR = Color(0, 255, 0, 0.5)

/**
 * The color to highlight grenades.
 */
var GRENADE_COLOR = Color(0, 255, 0, 1.0)


///////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////// --- MISCELLANEOUS --- ////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Paints the models with their respective colors.
 *
 * WARNING: This may cause random game crashes if you enable it.
 */
var COLOR_MODELS = false
The root cause was thrown at: AbstractDeclarationProviderFactory.java:44
        at org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:41)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:449)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtVisitor.visitScript(KtVisitor.java:78)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:73)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:515)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:83)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:58)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.registerDeclarations(LazyTopDownAnalyzer.kt:73)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitKtFile(LazyTopDownAnalyzer.kt:91)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:509)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.java:246)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.java:226)
        at org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitElement(ExceptionWrappingKtVisitorVoid.kt:27)
        at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
        at org.jetbrains.kotlin.psi.KtVisitor.visitKtFile(KtVisitor.java:73)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:69)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:509)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.java:246)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.java:226)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:187)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:56)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplCodeAnalyzer.doAnalyze(ReplCodeAnalyzer.kt:109)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplCodeAnalyzer.analyzeReplLine(ReplCodeAnalyzer.kt:102)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.compile(GenericReplCompiler.kt:71)
        at org.jetbrains.kotlin.cli.common.repl.GenericReplCompilingEvaluator.compileAndEval(GenericReplCompilingEvaluator.kt:36)
        at org.jetbrains.kotlin.cli.common.repl.ReplAtomicEvalAction$DefaultImpls.compileAndEval$default(ReplApi.kt:144)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:61)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:71)
        at com.charlatano.Charlatano.main(Charlatano.kt:43)
Caused by: java.lang.IllegalStateException: Cannot find package fragment for file Line_5.kts with package com.charlatano.settings
        at org.jetbrains.kotlin.resolve.lazy.declarations.AbstractDeclarationProviderFactory.diagnoseMissingPackageFragment(AbstractDeclarationProviderFactory.java:44)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplCodeAnalyzer$ScriptMutableDeclarationProviderFactory.diagnoseMissingPackageFragment(ReplCodeAnalyzer.kt:158)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.getMemberScopeDeclaredIn(LazyDeclarationResolver.java:262)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.findClassDescriptor(LazyDeclarationResolver.java:85)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.getScriptDescriptor(LazyDeclarationResolver.java:77)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitScript(LazyTopDownAnalyzer.kt:84)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:515)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:83)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:58)
        at org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:32)
        ... 35 more

```

Is that because of some weird dependencie problem or cant I use the build.bat? Please help ;)

Oh I forgot: https://github.com/4103/Charlatano
Thats my fork with the Changes

(First real Issue in days huh)

**Comment by Austin72** [comment]
I see the issue lol

take a look at what you changed in https://github.com/4103/Charlatano/commit/80bcddd8a26a1a30e866e27d931b050d351641d5

**Comment by 4103** [comment]
Oh shit. That was fast and I was dumb
Testing rn

**Comment by 4103** [comment]
Jo @Austin72 it works now. I dont know how I could oversee such obvious shit... I looked at all Dojo Stuff and tried to understand gradlew and I just fucked up that retarded easy stuf. THANKS MATE
