### ISSUE TITLE
Having the same problem as everyone else..

### ISSUE THREAD

**Issue by facoo** [Jire/Charlatano#42]
I can't fix it tried everything updated java and shit.. is there anything i can do else, it's not downloading anything im only getting the error then thats it. 

`WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please
ure bin/idea.properties is present in the installation directory.
        at com.intellij.openapi.application.PathManager.getHomePath(PathMa.... ETC!`

**Comment by hYsilg** [comment]
+1 same problem, full log:
WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
        at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:95)
        at com.intellij.openapi.application.PathManager.getBinPath(PathManager.java:132)
        at com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:311)
        at com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
        at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:77)
        at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:69)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:51)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:47)
        at com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:66)
        at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)
        at com.intellij.openapi.vfs.impl.ZipHandler.getZipFileHandle(ZipHandler.java:103)
        at com.intellij.openapi.vfs.impl.ZipHandler.createEntriesMap(ZipHandler.java:82)
        at com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:124)
        at com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:40)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:37)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:33)
        at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:50)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:286)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.classpathRoots(KotlinCoreEnvironment.kt:213)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:155)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:110)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:340)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericReplChecker.kt:68)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:42)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:46)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:53)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplScriptEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:55)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:68)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:42)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:63)
        at com.charlatano.Charlatano.main(Charlatano.kt:36)
warning: some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
warning: library has Kotlin runtime bundled into it

**Comment by Krouzu** [comment]
Have you guys installed the Java SDK located here? http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
