### ISSUE TITLE
Error on macOS

### ISSUE THREAD

**Issue by ningwang747** [Jire/Charlatano#497]
WARN: [kts] kotlin.script.experimental.dependencies.DependenciesResolver.NoDependencies must have a constructor without required parameters
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.text.StringFactory (file:/Users/ningwang/Data/Game/Hack/CSGO/Charlatano/Charlatano%201.0.6.jar) to constructor java.lang.String(char[],boolean)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.text.StringFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" javax.script.ScriptException: error: unresolved reference: java
import java.awt.event.KeyEvent
       ^
error: unresolved reference: KeyEvent
BUNNY_HOP_KEY = KeyEvent.VK_SPACE
                ^

	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:65)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.charlatano.utils.Dojo.script(Dojo.kt:32)
	at com.charlatano.Charlatano.loadSettings(Charlatano.kt:71)
	at com.charlatano.Charlatano.main(Charlatano.kt:43)
s-MacBook-puro:Charlatano ningwang$ sudo /Users/ningwang/Data/Game/Hack/CSGO/Charlatano/CSGOCharlatanoHax.sh 
Password:
WARN: [kts] kotlin.script.experimental.dependencies.DependenciesResolver.NoDependencies must have a constructor without required parameters
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.text.StringFactory (file:/Users/ningwang/Data/Game/Hack/CSGO/Charlatano/Charlatano%201.0.6.jar) to constructor java.lang.String(char[],boolean)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.text.StringFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" javax.script.ScriptException: error: unresolved reference: java
import java.awt.event.KeyEvent
       ^
error: unresolved reference: KeyEvent
BUNNY_HOP_KEY = KeyEvent.VK_SPACE
                ^

	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:65)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.charlatano.utils.Dojo.script(Dojo.kt:32)
	at com.charlatano.Charlatano.loadSettings(Charlatano.kt:71)
	at com.charlatano.Charlatano.main(Charlatano.kt:43)

**Comment by bonzobudy** [comment]
Well, this cheat is for Windows, so I guess that makes sense.


It's like holy shit you people are fucking retarded. :joy:

**Comment by w-o-a-h** [comment]
this only works on windows sorry

**Comment by ningwang747** [comment]
ty
