### ISSUE TITLE
not working after16 march update

### ISSUE THREAD

**Issue by anurag01021996** [Jire/Charlatano#65]
aftere the update whenever i run it...it gives error like this
"WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make s
ure bin/idea.properties is present in the installation directory.
        at com.intellij.openapi.application.PathManager.getHomePath(PathManager.
java:95)
        at com.intellij.openapi.application.PathManager.getBinPath(PathManager.j
ava:132)
        at com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoa
der.java:311)
        at com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:
48)
        at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUti
l.java:77)
        at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.j
ava:69)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.
java:51)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.
java:47)
        at com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache
.java:66)
        at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)

        at com.intellij.openapi.vfs.impl.ZipHandler.getZipFileHandle(ZipHandler.
java:103)
        at com.intellij.openapi.vfs.impl.ZipHandler.createEntriesMap(ZipHandler.
java:82)
        at com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHan
dler.java:124)
        at com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandle
r.java:40)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarF
ileSystem.java:37)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarF
ileSystem.java:33)
        at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(Co
reJarFileSystem.java:50)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRo
ot(KotlinCoreEnvironment.kt:286)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRo
otToVirtualFile(KotlinCoreEnvironment.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.classpath
Roots(KotlinCoreEnvironment.kt:213)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(Ko
tlinCoreEnvironment.kt:155)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(Ko
tlinCoreEnvironment.kt:110)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion
.createForProduction(KotlinCoreEnvironment.kt:340)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericRe
plChecker.kt:68)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericR
eplCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericR
eplCompiler.kt:42)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$r
eplCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:46)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$r
eplCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$l
ocalEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:53)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$l
ocalEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etReplScriptEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:55)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:68)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
eval(KotlinJsr223JvmScriptEngineBase.kt:42)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:63)
        at com.charlatano.Charlatano.main(Charlatano.kt:36)
warning: some JAR files in the classpath have the Kotlin Runtime library bundled
 into them. This may cause difficult to debug problems if there's a different ve
rsion of the Kotlin Runtime library in the classpath. Consider removing these li
braries from the classpath or use '-Xskip-runtime-version-check' to suppress thi
s warning
warning: library has Kotlin runtime bundled into it"
why its occuring?

**Comment by SoapTheFLyingDragon** [comment]
same here..

**Comment by HRVAT007** [comment]
Only thing not working for me is triggerbot.

**Comment by vovashahov** [comment]
HRVAT007 how u fix? bcs still not workinf after update

**Comment by HRVAT007** [comment]
You need to download charlatano master and you that by doing this https://github.com/Jire/Charlatano/archive/master.zip and than running build.bat file.
After building is done you should go in build folder and copy charlatano 0.9.7 folder and start is as you normally would. And you will have to redo you settings since old don't work for some reason at least for me.

**Comment by vovashahov** [comment]
HRVAT007, i have this error when im start BUILD.bat 
![error compile](https://cloud.githubusercontent.com/assets/26481851/24051343/712aac3e-0b3a-11e7-8b22-552ea319f88b.png)

**Comment by HRVAT007** [comment]
Do this to fix that :) https://www.youtube.com/watch?v=jLArUJt-tBs

**Comment by vovashahov** [comment]
HRVAT007, so for start i need instal SDK java then do this operation?

**Comment by SquareHeadd** [comment]
How can I make the aimbot working after the update?

**Comment by HRVAT007** [comment]
You need JDK, aimbot is working for me I don't know why it is not working for you.

**Comment by vovashahov** [comment]
HRVAT007, ok, i will write here after. thx mate)

**Comment by HRVAT007** [comment]
NP.

**Comment by vovashahov** [comment]
HRVAT007, thx bro. all worked 🥉

**Comment by SquareHeadd** [comment]
I can't do it , Im kinda noob at this stuff. Can someone add a already built one please?

**Comment by LefsFlarey** [comment]
@SquareHeadd, this is my private flavour of Charlatano, with some slight tweaks to certain settings and unlike Charlatano, is built with a special tool so it's detection rate should be way lower than public Charlatano. Try at your own risk.
[charlotte.zip](https://github.com/Jire/Charlatano/files/851393/charlotte.zip)

**Comment by SquareHeadd** [comment]
@LefsFlarey Charlotte:D , thank you . u said "with some slght tweaks to certain setting" 
can you tell me what kind without getting into too much detail?

**Comment by alexlop2208** [comment]
did everything with the JAVA_HOME yet i still get the error that's in the first comment
can someone help ?

**Comment by yuka123** [comment]
ye me too, same error.

**Comment by LefsFlarey** [comment]
@SquareHeadd, I changed the default settings to disable everything except walls, for my own personal preference but those can be changed back. Generally, the biggest difference of my flavour is that I incorporated some stuff into the hack to make it less 'vac'-able

**Comment by SquareHeadd** [comment]
another update. not working .:(

**Comment by Baffy** [comment]
tnx for this man worked

**Comment by SquareHeadd** [comment]
@Baffy Worked? , well it's not working for me man wtf.

**Comment by anurag01021996** [comment]
i have compiled the charlatano 0.9.7 but still its not working
it says
"WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make s
ure bin/idea.properties is present in the installation directory.
        at com.intellij.openapi.application.PathManager.getHomePath(PathManager.
java:95)
        at com.intellij.openapi.application.PathManager.getBinPath(PathManager.j
ava:132)
        at com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoa
der.java:311)
        at com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:
48)
        at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUti
l.java:77)
        at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.j
ava:69)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.
java:51)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.
java:47)
        at com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache
.java:66)
        at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)

        at com.intellij.openapi.vfs.impl.ZipHandler.getZipFileHandle(ZipHandler.
java:103)
        at com.intellij.openapi.vfs.impl.ZipHandler.createEntriesMap(ZipHandler.
java:82)
        at com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHan
dler.java:124)
        at com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandle
r.java:40)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarF
ileSystem.java:37)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarF
ileSystem.java:33)
        at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(Co
reJarFileSystem.java:50)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRo
ot(KotlinCoreEnvironment.kt:286)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRo
otToVirtualFile(KotlinCoreEnvironment.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.classpath
Roots(KotlinCoreEnvironment.kt:213)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(Ko
tlinCoreEnvironment.kt:155)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(Ko
tlinCoreEnvironment.kt:110)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion
.createForProduction(KotlinCoreEnvironment.kt:340)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericRe
plChecker.kt:68)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericR
eplCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericR
eplCompiler.kt:42)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$r
eplCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:46)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$r
eplCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$l
ocalEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:53)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$l
ocalEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etReplScriptEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:55)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:68)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
eval(KotlinJsr223JvmScriptEngineBase.kt:42)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:63)
        at com.charlatano.Charlatano.main(Charlatano.kt:36)
warning: some JAR files in the classpath have the Kotlin Runtime library bundled
 into them. This may cause difficult to debug problems if there's a different ve
rsion of the Kotlin Runtime library in the classpath. Consider removing these li
braries from the classpath or use '-Xskip-runtime-version-check' to suppress thi
s warning
warning: library has Kotlin runtime bundled into it"

please someone help me with it

**Comment by anurag01021996** [comment]
@LefsFlarey when i try to start charlotte..it says 
"Error: Could not find or load main class com.charlatano.Charlatano
Press any key to continue . . ."
any solution?

**Comment by Jire** [comment]
Should be fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
