### ISSUE TITLE
ERROR / Exception in thread "main" .

### ISSUE THREAD

**Issue by gosugosusado** [Jire/Charlatano#685]
Exception in thread "main" javax.script.ScriptException: error: unresolved reference: GARBAGE_COLLECT_ON_START
GARBAGE_COLLECT_ON_START = true
^

        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:65)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:83)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)
Pressione qualquer tecla para continuar. . .

HELP PLS? @Jire

**Comment by unlimitedsola** [comment]
change `GARBAGE_COLLECT_ON_START` to `GARBAGE_COLLECT_ON_MAP_START `
