### ISSUE TITLE
Not Working Again using latest version ;(

### ISSUE THREAD

**Issue by pakboy** [Jire/Charlatano#70]
I have The error :(
I Think need to update  :+1: 
Exception in thread "main" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.ClassTable$name$2.invoke(ClassTable.kt:34
)
        at com.charlatano.game.netvars.ClassTable$name$2.invoke(ClassTable.kt:28
)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:153)
        at com.charlatano.game.netvars.ClassTable.getName(ClassTable.kt)
        at com.charlatano.game.netvars.NetVars.load(NetVars.kt:49)
        at com.charlatano.game.CSGO.initalize(CSGO.kt:113)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)

**Comment by ArkEcko** [comment]
adding the roots and adding in JAVA_HOME with java jdk fixed that problem for me this explains how to do so ---> https://www.youtube.com/watch?v=4lMx98pEBsM&index=1&list=LLhsotIA97IOPDdzuZZV4d1w

**Comment by MoofMonkey** [comment]
Close, solved.
