### ISSUE TITLE
AIM NOT work.

### ISSUE THREAD

**Issue by gosugosusado** [Jire/Charlatano#716]
Exception in thread "Thread-7" Exception in thread "Thread-6" java.lang.IllegalArgumentException: bound must be positive
        at java.util.concurrent.ThreadLocalRandom.nextInt(Unknown Source)
        at com.charlatano.utils.RandomKt.randInt(Random.kt:27)
        at com.charlatano.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt:88)
        at com.charlatano.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
java.lang.IllegalArgumentException: bound must be positive
        at java.util.concurrent.ThreadLocalRandom.nextInt(Unknown Source)
        at com.charlatano.utils.RandomKt.randInt(Random.kt:27)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt:88)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

Flat aim/ Path aim

**Comment by gosugosusado** [comment]
Work after reinstall.

**Comment by 10jasper10** [comment]
bound must be positive.
You must have broke a setting putting it below the minimum.
