### ISSUE TITLE
Error when using Charlatano in MM

### ISSUE THREAD

**Issue by doctormooshe** [Jire/Charlatano#740]
Exception in thread "main" javax.script.ScriptException: error: expecting an element
import com.charlatano.settings.*
          ^
error: expecting an element
import com.charlatano.settings.*
                     ^
error: expecting an element
import com.charlatano.settings.*
                              ^

        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:65)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:82)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)
Press any key to continue . . . Pls help

**Comment by ExpiredRamen172** [comment]
I have this same error
