### ISSUE TITLE
NPE on CS:GO today's update

### ISSUE THREAD

**Issue by luismelodev** [Jire/Charlatano#794]
`Exception in thread "Thread-7" Exception in thread "Thread-5" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getITeamNum(NetVarOffsets.kt)
        at com.charlatano.game.entity.EntityKt.team(Entity.kt:53)
        at com.charlatano.scripts.esp.GlowESPKt$glowEsp$$inlined$every$1.invoke(Every.kt:44)
        at com.charlatano.scripts.esp.GlowESPKt$glowEsp$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFFlags(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.flags(Player.kt:61)
        at com.charlatano.game.entity.PlayerKt.onGround(Player.kt:63)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt:30)
        at com.charlatano.game.hooks.OnGroundKt$onGround$1.invoke(OnGround.kt)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(Every.kt:42)
        at com.charlatano.scripts.BunnyHopKt$bunnyHop$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "Thread-11" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFlFlashMaxAlpha(NetVarOffsets.kt)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt:32)
        at com.charlatano.game.hooks.OnFlashKt$onFlash$1.invoke(OnFlash.kt)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.invoke(Every.kt:42)
        at com.charlatano.scripts.ReducedFlashKt$reducedFlash$$inlined$invoke$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "Thread-12" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getFlC4Blow(NetVarOffsets.kt)
        at com.charlatano.game.entity.BombKt.blowTime(Bomb.kt:41)
        at com.charlatano.scripts.BombTimerKt$bombUpdater$$inlined$every$1.invoke(Every.kt:48)
        at com.charlatano.scripts.BombTimerKt$bombUpdater$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "Thread-8" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getHActiveWeapon(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.weaponIndex(Player.kt:50)
        at com.charlatano.game.entity.PlayerKt.weaponEntity(Player.kt:54)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt:43)
        at com.charlatano.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "Thread-9" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getHActiveWeapon(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.weaponIndex(Player.kt:50)
        at com.charlatano.game.entity.PlayerKt.weaponEntity(Player.kt:54)
        at com.charlatano.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt:43)
        at com.charlatano.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "Thread-6" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getHActiveWeapon(NetVarOffsets.kt)
        at com.charlatano.game.entity.PlayerKt.weaponIndex(Player.kt:50)
        at com.charlatano.game.entity.PlayerKt.weaponEntity(Player.kt:54)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt:43)
        at com.charlatano.scripts.RCSKt$rcs$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Exception in thread "Thread-4" kotlin.KotlinNullPointerException
        at com.charlatano.game.netvars.NetVar.getValue(NetVar.kt:31)
        at com.charlatano.game.netvars.NetVarOffsets.getSurvivalGameRuleDecisionTypes(NetVarOffsets.kt)
        at com.charlatano.game.hooks.EntityIterationKt$$special$$inlined$observable$1.afterChange(Delegates.kt:76)
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
        at com.charlatano.game.hooks.EntityIterationKt.setState(EntityIteration.kt)
        at com.charlatano.game.hooks.EntityIterationKt.access$setState$p(EntityIteration.kt:1)
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inlined$every$1.invoke(Every.kt:42)
        at com.charlatano.game.hooks.EntityIterationKt$constructEntities$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)`

**Comment by ias-t** [comment]
what should we do with that ?

**Comment by luishmelo** [comment]
Debug
