### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by revengecommando** [Jire/Charlatano#850]
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngineFactory not found
Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:88)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)
Press any key to continue . . .

**Comment by revengecommando** [comment]
[https://prnt.sc/ob3pq0](url)
