### ISSUE TITLE
Charlatano wont open

### ISSUE THREAD

**Issue by adisbe** [Jire/Charlatano#859]
when i try and open it says
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngineFactory not found
Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:88)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)
Press any key to continue . . .

how do i fix this?

**Comment by Maze543** [comment]
same
