### ISSUE TITLE
Does not activate

### ISSUE THREAD

**Issue by Maze543** [Jire/Charlatano#861]
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngineFactory not found
Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:88)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)

**Comment by LokiLucas** [comment]
I have the exact same issue

**Comment by x7airworker** [comment]
Duplicate of #859

**Comment by cartilage-ftw** [comment]
Bump. Same problem here. I built using an old version of jdk 8

**Comment by Bobby8904** [comment]
ANy idea how to fix i am getting same issue
