### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LokiLucas** [Jire/Charlatano#865]
When I open the "Start Charlanto 1.0.11" it doesn't come about with a blank page it comes up with 

ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngineFactory not found
Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:88)
        at com.charlatano.Charlatano.main(Charlatano.kt:40)

So kind of unsure what to do at this point

**Comment by apples12** [comment]
True using the master instead, from what I read its having a compiling issue, dunno how to fix it as java is not my forte.
