### ISSUE TITLE
it used to work but suddenly i got this. previously i used ratpoison and i got the same error. i do have the dll at that location tho

### ISSUE THREAD

**Issue by ThiccTomato** [Jire/Charlatano#880]
java.lang.UnsatisfiedLinkError: C:\Users\Admin\AppData\Local\Temp\libgdx??????\dc0f0009\lwjgl64.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:744)
        at java.base/java.lang.System.load(System.java:1873)
        at org.lwjgl.Sys$1.run(Sys.java:70)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:87)
        at org.lwjgl.Sys.<clinit>(Sys.java:117)
        at org.lwjgl.openal.AL.<clinit>(AL.java:59)
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.<init>(OpenALAudio.java:72)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:88)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:69)
        at com.charlatano.overlay.Overlay.open(Overlay.kt:58)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:97)
        at com.charlatano.Charlatano.main(Charlatano.kt:43)
Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
        at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:591)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by TheProfessorJJ** [comment]
Is it fixed?

**Comment by ThiccTomato** [comment]
> Is it fixed?

no
