### ISSUE TITLE
bomb timer doesnt work

### ISSUE THREAD

**Issue by ThiccTomato** [Jire/Charlatano#882]
if the bomb timer is enabled i get this error:
Exception in thread "DefaultDispatcher-worker-1" java.lang.UnsatisfiedLinkError: C:\Users\Admin\AppData\Local\Temp\lwjgl??????\3.2.1-SNAPSHOT\lwjgl.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:765)
        at java.base/java.lang.System.load(System.java:1834)
        at org.lwjgl.system.Library.loadSystem(Library.java:162)
        at org.lwjgl.system.Library.loadSystem(Library.java:152)
        at org.lwjgl.system.Library.loadSystem(Library.java:116)
        at org.lwjgl.system.Library.loadSystem(Library.java:67)
        at org.lwjgl.system.Library.<clinit>(Library.java:50)
        at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
        at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
        at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
        at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:673)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by ThiccTomato** [comment]
ayo sb pls help ):
