### ISSUE TITLE
Asking for Assistance about csgo windows title

### ISSUE THREAD

**Issue by jackieyiwu** [Jire/Charlatano#892]
When I play on a community platform, the title of the CSGO window will become a random description, how can i fix it ?

**Comment by jackieyiwu** [comment]
Exception in thread "Thread-2" java.lang.NullPointerException
at com.charlatano.game.CSGO$initialize$$inlined$every$2.invoke(Every.kt:42)
at com.charlatano.game.CSGO$initialize$$inlined$every$2.invoke(Every.kt)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by DeyanSimeonov96** [comment]
Join the newest Charlatano Community Discord on: https://discord.gg/7E64tn

Hi if you have any question or need help about settings and everything about this cheat join discord thank you
