### ISSUE TITLE
 Charlatano1.1.0 NullPointerException in Charlatano.kt Line 91

### ISSUE THREAD

**Issue by mister91jiao** [Jire/Charlatano#974]
Caused by function evale(code) , i am C#programmer I can't fix it，sorry

**Comment by wesleybs29** [comment]
I'm having the same problem 

 Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:91)
        at com.charlatano.Charlatano.main(Charlatano.kt:43)
        at com.charlatano.Charlatano.main(Charlatano.kt)

**Comment by znoorss** [comment]
I'm also having same issue.

Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:91)
        at com.charlatano.Charlatano.main(Charlatano.kt:43)
        at com.charlatano.Charlatano.main(Charlatano.kt)

**Comment by pixiwoo** [comment]
![charliee](https://user-images.githubusercontent.com/76404151/102720230-81607300-42f3-11eb-8fd1-ffe246baf66b.jpg)
Same here.
1.0.12 works good

**Comment by kalilc** [comment]
Same here. Tried with JDK 11 and 15.

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "$this$with" is null

        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:91)
        at com.charlatano.Charlatano.main(Charlatano.kt:43)
        at com.charlatano.Charlatano.main(Charlatano.kt)

**Comment by gdaxz** [comment]
did any of you manage to fix this error? if they didn’t, please tell me if using a previous version of Charlatano is it still safe?

**Comment by kalilc** [comment]
> did any of you manage to fix this error? if they didn’t, please tell me if using a previous version of Charlatano is it still safe?

Haven't got time to deal with it for now. Version 1.0.12 still working and safe. Safety is not related to new version, most of times its new stuff or stuff that stopped working, not related to being detected.

**Comment by gdaxz** [comment]
oh ok thanks
