### ISSUE TITLE
1.15 not working?

### ISSUE THREAD

**Issue by marcl200** [Jire/Charlatano#992]
when opening the command prompt window you are 1. unable to type in it and 2. none of it works in game.

**Comment by jeremyhuang123123** [comment]
not working for me as well,  when opening promt command it showed: 
Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:89)
        at com.charlatano.Charlatano.main(Charlatano.kt:44)

**Comment by nix9191** [comment]
for me is working try to reinstall the cheat from zero install last java jdk

**Comment by Jire** [comment]
Try version [1.2.0](https://github.com/Jire/Charlatano/releases/tag/1.2.0)
