### ISSUE TITLE
1.2.0 problem

### ISSUE THREAD

**Issue by bullshit277** [Jire/Charlatano#995]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/C:/Users/Tayfun/Desktop/Charlatano-master/build/Charlatano%201.2.0/Charlatano%201.2.0.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.Error: Structure.getFieldOrder() on class com.charlatano.overlay.transparency.win10.AccentPolicy does not provide enough names [0] ([]) to match declared fields [4] ([AccentFlags, AccentState, AnimationId, GradientColor])
        at com.sun.jna.Structure.getFields(Structure.java:1077)
        at com.sun.jna.Structure.deriveLayout(Structure.java:1232)
        at com.sun.jna.Structure.calculateSize(Structure.java:1159)
        at com.sun.jna.Structure.allocateMemory(Structure.java:401)
        at com.sun.jna.Structure.ensureAllocated(Structure.java:377)
        at com.sun.jna.Structure.ensureAllocated(Structure.java:367)
        at com.sun.jna.Structure.size(Structure.java:434)
        at com.charlatano.overlay.transparency.win10.Win10TransparencyApplier.applyTransparency(Win10TransparencyApplier.kt:37)
        at com.charlatano.overlay.Overlay.open(Overlay.kt:79)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:97)
        at com.charlatano.Charlatano.main(Charlatano.kt:44)

**Comment by Jire** [comment]
Should be fixed in [1.2.2](https://github.com/Jire/Charlatano/releases/tag/1.2.2)
