### ISSUE TITLE
Error while opening the new update

### ISSUE THREAD

**Issue by Ariarad** [Jire/Charlatano#998]
Hi, I have a problem with the new update 1.11.0, when I open the cheat it comes up with an error :

Exception in thread "main" java.lang.NullPointerException
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:91)
        at com.charlatano.Charlatano.main(Charlatano.kt:43)
        at com.charlatano.Charlatano.main(Charlatano.kt)
Press any key to continue . . .
---------------------------------------------------------------------------------------
by the way! can sb give me the discord server link?! I'll be appreciated.

**Comment by Jire** [comment]
Use a newer version: [1.2.3](https://github.com/Jire/Charlatano/releases/tag/1.2.3)
